### ISSUE TITLE
Tested this from VSTS?

### ISSUE THREAD

**Issue by holmesb** [lmammino/webhook-tunnel#1]
Trying from VSTS to Jenkins using command:
`node /usr/local/bin/webhook-tunnel --log-level debug -p <port> https://jenkins.example.com`

When VSTS sends a webhook, webhook-tunnel shows the following error:
> [2018-08-15T15:21:09.511Z] INFO (webhook-tunnel/1 on webhook-proxy-76c69dd7bf-gs4wv): Incoming request: GET /git/notifyCommit?url=<VSTS GIT PATH>&branches=master
> [2018-08-15T15:21:09.530Z] ERROR (webhook-tunnel/1 on webhook-proxy-76c69dd7bf-gs4wv): unable to verify the first certificate
>     Error: unable to verify the first certificate
>         at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
>         at emitNone (events.js:106:13)
>         at TLSSocket.emit (events.js:208:7)
>         at TLSSocket._finishInit (_tls_wrap.js:639:8)
>         at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)

Anyone successfully used this from VSTS rather than GitHub, or otherwise seen this error before?  VSTS shows error "Bad Gateway (502)" when we test the webhook.

We've tried following the [advice here ](https://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs)to install ssl-root-cas package ('npm install --global ssl-root-cas'), then adding the below line to [the top of index.js](https://github.com/holmesb/webhook-tunnel/blob/78e5ed9604a733a201b1bf05d684ae9bf2e24c99/src/index.js#L6):

`require('https').globalAgent.options.ca = require('ssl-root-cas/latest').create();`

Same problem occurs, but I'm a node.js newb, so not sure if that's the correct place to insert this line.  Any ideas?

**Comment by lmammino** [comment]
hello @holmesb, sorry for the slightly delayed reply.

[`http-proxy`](https://npm.im/http-proxy), the dependency used by this module to do the proxying, supports [different scenarios with HTTPS](https://www.npmjs.com/package/http-proxy#using-https) but those are not directly exposed in the CLI here.

What use case are you trying to support among the 3 explained in the `http-proxy` docs?

It would probably make sense to create more options in the CLI here to be able to support some of those.

**Comment by holmesb** [comment]
Well both VSTS and Jenkins are HTTPS, but I'm trying to implement webhook-tunnel any way at all to begin with, so is on HTTP currently.  Does that make my scenario HTTPS --> HTTP?

**Comment by lmammino** [comment]
If I am reading the documentation correctly, your case should be HTTP (proxy) -> HTTPS (destination).
In this case you shouldn't need any certificate, but we should somehow be able to provide some extra config.

If you are able to change the code in your setup you could try to change [line #80](https://github.com/lmammino/webhook-tunnel/blob/master/src/index.js#L80) as follows:

```javascript
const proxy = httpProxy.createProxyServer({
  target: {
      host: argv.target,
      protocol: 'https:',
      port: 443
  }
})
```

Then pass only the domain to `argv.target`.

Let me know if you can try this and if it is enough to get it working.

**Comment by holmesb** [comment]
Hi,
Thx for the suggestion, but no luck.  Same error.  I've also tried disabling TLS verification completely by adding:
`process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = "0"`
[to the top of index.js](https://github.com/holmesb/webhook-tunnel/blob/f8ae66591c276a3726fc73ae156479f5c9b0e1a9/src/index.js#L7).  
Is your Jenkins https?

**Comment by lmammino** [comment]
@holmesb, unfortunately not :(

**Comment by holmesb** [comment]
I figure I don't need TLS on the inside of webhook-tunnel.  Working fine using http instead. 
 Closing this issue.
