### ISSUE TITLE
Documentation for configuring

### ISSUE THREAD

**Issue by HarjeetPahuja** [lmammino/webhook-tunnel#5]
Hi,
Need more detailed documentation for configuring this. e.g. example command to the configured proxy server and how will get current server path which will need to expose

**Comment by lmammino** [comment]
Hello @HarjeetPahuja, I have a good amount of info (including [config](https://github.com/lmammino/webhook-tunnel#command-line-options)) in the README.

I am not sure I fully understand your question in relation to what's currently available there.

Also, remember that this is an open source project, so I'd love for other people to contribute and make it better, where they see room for improvement. If you think that's the case, please submit a PR.

**Comment by HarjeetPahuja** [comment]
Thanks
